### ISSUE TITLE
The config file table_master_local_attn_new_decoder_FinTabNet_full_img520_win300_0_tag600_cell150_batch4 is missing

### ISSUE THREAD

**Issue by uobinxiao** [namtuanly/MTL-TabNet#4]
The config file used in table_recognition_dist_train.sh is missing.

**Comment by namtuanly** [comment]
This is the config in my other experiment. Please use the config in MTL-TabNet/configs/textrecog/master/table_master_ResnetExtract_Ranger_0705_cell150_batch4.py (for the PubTabNet dataset) or in table_master_ResnetExtract_Ranger_0705_FinTabNet_cell150_batch4.py (for FinTabNet).

**Comment by uobinxiao** [comment]
Thank you very much for the reply. I close this issue.
